language: python
sudo: false
cache: false
python:
- '3.5'
addons:
  postgresql: '9.4'
env:
  global:
  - secure: rLuzE+/3WVxra5ssD9MdVqTsuVcRc0PpOrc4FayueQ9y/CcjXuxFtU9NpS88DDwAyGc/7wCPLmRKAzsNTMgDjfHkKXa8VfhI9zZ7HOEI1suVJakkJFXTwajH1X+ACDICoQocrmuOesIMrlAm1qhrSnxHLZuIZ5y3qEGPaSvCMa9JPX9U8huJuhwukxiunpeoApeJclRK7HjLhrAIZVuBNZnyNjiqmNFXPFdGbpcdUGsqNrZQGZa9vlED2dXmqqsIhL7/ghR1sSvIzjVBEi2Ig9wu1QWO5LuAzgO6wIfuOh1gbQ1Z24bYLTeugApwI2eNRe5Rn7F+RXVCYbjetj/0twIXKr6NkSgaLt1c+2b7yIOLRpRl0kpahZc+TsQ3ja03UelpXhH8c0De+6sUvmofs39RgdMSjYBcaY5hDl1b5oZOcZDhQYYAiFUJ3CKIM82WgvTD/phcarf9e0lbrVFIK17P/QixUPAKUS+IfS53r10QO1DTN+0vpLcUh659u8gLxHlbTVkGPfuWRXVhPCmSlHZXqM22gVois5ch97FEm7sgLlJP5hHg1q+utvXV4YDM0m+5SicjGeTyh7ZNszBiMuCu9Na5NaUyhb3XS8niLPwXUzNKcUs0NXckakpqBxstAE4Zyqf3HmmzFQCNvdrFnk6fuRXo1nxtRi1K3N/zf4k=
  - secure: o8lh6ewarKq9cNb465Nlivp3zIHeWBWT2xgXldG/cvB3l0LMjSpxkXQ9b+/bmuGcUKYqbrOjXyRoqxf+9oqiwDFYCAqb3JwRVyj58y7qJDyfgXo762cTO39PiuqVh+CsGh/zNOEVtlqFS/ZyKJHWLSQaioKVKvJpXViz4Fm5vU65fnAHrBce4uPO0TfVWbsSBthZd0aqr/OWQKmuPst3yqtahm4FoXWi9xY5PLBoUHevoJ7YQUby0HlatrS7RcD1m1Gq2+NByYpMS0gsaW7BVCRE/Tvsd9Z9tERFPH7T5IHdW/vj1J3O6F3aQj8R21pBtAbrg+TL2PmoMoh/reZtFWZ+KuezkV61dYwSoz8c3lRVMQfa99Q4B7AmTnhQ+lXoZ1A7ZOZcbUIr0demY9dnJ4BCAjrCP18dPuMQ4ZI/VUThUWpcoDimMWLOa/BNGcWVh9gbW9z8RFnjlzTJqp/c/sK9x46LD3znsgT6vHO5OPWz5vEo4m6zipSdhIOhHuO03QYgJ6oouDLnz+JZKZAjW4mFx2137g8MTKSfYZzYKP4g/9VBM0HmlHOM+ESD2pUvNqNERpvsqJmHi9nH0M/F0+HJmc6d28sBqbdUsoX2XWanziepIxnQUQeRpJP3z0KUjQz9cGemihYxk4VKgCQdmLUIKOx+bIYlEDQredVM3n0=
  - secure: V7OTbVDWuY2VzPoML3nBf1vz50wmyzt7DmbrWch58ZTk1clR7K+Jqfns+T3CcDnJtnr5G3/A/aaV0wLza/Pw6gDT8keLTCi9Ru7rvLCW0diJME817ne12TJxYBsikUUVN9s8tw2F65me2Abp7J+uH250omtwTLYjThAHMjmF1oqhwmWTpvimg/z/eJS4TpNOGrD+ZJA/nmjtrBI7MQ8b4jPGKykpmQd7IUtVJ5PjiS7xJvPOLCl5VDGwlChlMBRXKpb6bLyErtoz3SVpH7c0UuDMTS2gB59BqAorf8q+Izj8Vy3p4CW3S40CtqSv+Hpz0IGGEPSiFYjSluyL0yWPvZUJYR/vuvBLelL0xpsC/Y3cTPxQIS3uTHvAG2NSfTiQK63p+0/x6f8uqZC7Ns5tw0aMUwY/ufFOe3SU1T+jG5snttZ8xi1FWD9je/muelY33VYD0W+v/VwIy15yiY+GEOn8cjg07p1aHOMeR4ddE1F/i24IWTTUxIW7NVqlcGimAGufELPY9XHXQL0JxKNSOa1xhIUe4yo8A9sMXbjkKmBxsV988GDjsWUZYTVhC/sVtmaq6V63SgwVFVWUGSG4m92xUKjwkB2QbqVCX8TbtLWeJZ5UUIHTH3iwfPWTYgF44H+nRqpca2uoLtXD8wp1fG9V+1aTd02f7In1GI2TFtc=
  - secure: BJlyqeLXYOa+bGLwCQP1ObpB0Wu3UhfpLS6PKz2w51r8RxxGdLmt/JB8f+UQufY9nHbZUMNDoodh+eoF4iuSmtK/xekUUGERBTRLV0Ajy/z7rOgeiDhhT6O8S41wYjcyTlzYCFFDWml9jQ7txIyvMxIER+JLwaBDOJPzJByS+gFqoeFF7GiMQI0Az+AukQJ1284p66G+KA2jlN4pe66gmiWJ6+9zF5CNK/qvnwV/1BcNLcEfgQpMGyAxr/yGZvFBuw5F/RWMILV41g9tF9qIGRIo10tF+QTaPjNG8rgy0/xTcEQp+CxBPLtygJ4pbgzRch/DwcPEyJPRO/wtjmB9yH0gb/h3w3veC5ysH2wWLvEJYsgbq+Ius877Sj5CmB8fVbr/RdGR/rmMqIiqhVhbBRf5oHAKio/W4nNwCA1kTWb3VeJAxcqVmUb0xIYX7vFyNwblMxgzFp+INsCXezcNNrheJz4R7MMzcWnuHzD3DsWIwVtDNgQm3im2oCRk7eow911bXt9khs47sHSuyQjJKpv6tbkXoCbbUBj3bcdh0B+LVbjQ46FT3KnZvlmYdDh0425Yk8R+8vXiADhI69CgKMsyC5W+G4QbV3COKCKvk46usiKAlSKdP+nijC/eDW/LB18nBtBymtIOnxH8C5vF+reR17ISOnA4OfZUequu/4g=
  - secure: mi7MWNNbp+JDs65KjRYGPNK88rSCiizwI9Szk9X2M5BbdlSjQuDeEtPEHry5yvbiTOA2oZaml5zAXxc6xOX9hpNTvZlfQ9ZDoPuczrIzhVpR+wDSpqdYOifvI1k6Mgi+8u2SEb6uhAzYwMrfKq/i+8MVzYhystVFTfwmxh58CQYHvYvdtojPW0TWylVdGdWdoBXdigzKw3iyPrxQYRHyK9NVoXvP2vvAYT0aRYgo2QHWn+DzciPArJjfGjoOJLA84hfG45Q2T1TK5hH+5zWJpRDNplt4JlVkiD0+W8rzulJkGTXJK6ZXa6Mmwatmc0xTEkj5m0pMO5pzYyUS8tmo5A9n2YYfw42X9iwni+k8X7HjPsN3oDzYQ8IO4wHe9lD1g7BlepWRIlnfoSo8snPYDQdtzFc3aYf1rE5RAs+wlZiQOG3h+5a7zD3a40D+cbY01gFFSEfv+MdHVVqqaiyWic6hvD+NCK0eyJNqHaSAY9q1Z4JFec/ZK9OE1BMS9W2VjOi4H/GFrEZCP9hgEk9DFzEINfc7wC2FcpJ0a14wsB0pGddoQSA0ffIFclIGnzDG2X4GuId7RB6iAq6AUMNYFIzS7JGIb4QA/9L94YapyHV0kj2AjGbwh22K6K8nZ+O6fgY7B3TcInk277q8T5bek+hFhP93oStoMKfrrQQ0+Ug=
  - secure: cF/RGQ2MNHxksiYQFQsoMhhlrMUy3peUEyHmjyWu9gmMwby60MDQk/ssIY41AUshdY6XuqlvV4DxER61bhyvbAbQR5BkY64GWifhusFmWwFPbz9sak4Tng1Jw5+AGJjyJUinLG5+rbQ9eakZFY2eYIzbY5i21Dm876wSgPNO0E1bGMfiObZQb3LqxTpitPw4YCuIpGKWCLlhkHNYUTmF0MZyAI2vNRi1QFfiPWxkM3YJpD11UPBRnVVt96+oJGmR2rITG1iHn3Q6KxAfCwrzxJD/+RrkK1ByelOxWUuqlOtgKJg963dDjMRHle7At0zpBFTPcHzHzPr/IlCYeIKh5hgtt9L/RrQd07r4LI4ayxZcYhonSZ71NjIThg+AiRTSn8ABx4ocs5zZpzG+guN2bAOQ3s+LoUWap0If33WV4ckc+4mRHxqWQkh2CnSebIsqh/J3OPPVsWxANDOmH+zWvPFdAMVWU5dgM/sdZzZ91nN29y/eRflvdrfEfJFThO010szlm98BowSJuEHoyF94f2GnuJI9cVo8qpbL1xR+YYgK+QwYGK7dnNIWczsjMxYcfh7wFB/GWVSwCR1UqXTFLw4QmJQqEu+FZoh6oKDi8fvRSJFBZo1uPUSU9/V9cSgLXvflQ9egbnEtf9OwcEANGqj7iXTtz3H38+0C21enqG0=
before_install:
- travis_retry pip install -U pip setuptools wheel
- export DATABASE_URL=postgresql://:@/cfdm_cms_unit_test
before_script:
- psql -c 'create database cfdm_cms_unit_test;' -U postgres
- travis_retry pip install -r requirements.txt
- travis_retry pip install coverage django_coverage_plugin
- ". $HOME/.nvm/nvm.sh"
- nvm install v5.5.0
- nvm use v5.5.0
- travis_retry npm install
- npm run build
script:
- "(cd fec && coverage run ./manage.py test)"
- npm run test-single
after_success:
- travis_retry pip install codecov
- "(cd fec && coverage xml)"
- codecov -X pycov
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
- tar xzvf $HOME/cf.tgz -C $HOME
- travis_retry cf install-plugin autopilot -f -r CF-Community
- npm run build
- DJANGO_SETTINGS_MODULE='fec.settings.production' python fec/manage.py collectstatic
  --noinput -v 0
- DJANGO_SETTINGS_MODULE='fec.settings.production' python fec/manage.py compress -v
  0
deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --login True --yes
  on:
    all_branches: true
dd:
  secure: aTfGVUc5LQwWD8syiDZL9jnXlXiz696VJZtjVkDMTRfsLQ0LscmuIN2MFhbwtviLNR1axpuNEHlE2HkXqLvA+G8xREqikyhJ5POX4rmTppOeOb8HnidhJQ7FQieMhGFL01bB+PGgugXQMTTJhWv6HgKoIsIr1Z1Ls/XSbeS14/DNXKnD4RAyUUgddb6K/RO7ZCBD5szh78Hh/0xP6iRJR7gZzqis8hE427vUX08w5GnIKRvqPRYcDq/i8KgRrm4dGISKqVofRkXoiGyfyr5G/A6rFq0TeQshjEVJlQQHdDbZRA+fbeLZFmejrlzoR+PyTkrTOBityLngWnr8Zzn1tcC2Q9IhPVFHOmghUlC4N8lm3S3WrW61OrZr/rc1mtHYisPHZFx4TqXA7e5A1T5L7/hmt46vDwyZXEzO7IMy6eQY2E/+eMZXELJfhR4bPudHmEYfhb3v6AqLD+0BTdG67VMw3sSysUEQ1upW8rnzvWkcnhP+Z2OKHNCZtenBzMbWggHf79IaIAzCJhVb9Az+b0Qs1pps/sTu24q9jmug8A61t/Yi+SGZkhjsKO2qM3cUhQe1/zn0eRe3sJg+H8MwsAzSlpN9zyIUhJWVSbxWTMV+NuKBpcOWZ3LW1W+DfY+iEOdhpzmLq7Ewc/fKPacKOX3QIg0xDd7q+PDETZHICWo=
