language: python

sudo: false

cache: false

python:
  - "3.5"

addons:
  postgresql: "9.4"

env:
  global:
    - secure: "P4T1SVLTY0rlA3wXbTKJZU3wUr8hte0NBRTne51Wu/owd48ytrUIPYJTpxZtl6XMYxIsWmdxhl8daVJVUWkRy6l0bvbUFZeZGbL9r/AuxZLkkHE10LA9XIiOZtMnvRQ6OCJ97Pq+eKjh1hSgYlHm6b60Uz/VKw13uSvm+i0cNNKUePMn6hfzpuzBALqZEYhPxJ/7I5q1imjYYuFQNXTZooHxf0gImG72CDu/R15cS2F4iADzn/Hfnl4rpbIVFghkKkCYEhj30JyU4AhB2D/I6Obco0af8MhV4PMcXBLByN5Gb65xSpKPFlpKgqSSXAoerR+69ok8o0dVAJmq4IN3IxuJWiOGSZFbWWHUbmp01fAgrhgS8YFLU8np0J0fKEqod/2t7n7aerY/FKqGXUxdK7aH3W0ZNUteE6cigIZlcwrdPOWyj1rKMAZMv2DZdxEV5iI31HfTzHIlQEECAp+L2nXJtaAf38q5BV5mqpFohLgovcF9uGGadZFFVUG6B/apCFn8W3qVrVWpvPiVz3nf7CZA3gDT1dN4t79VYw1ntwgDM47zMOwGJMEk0rUcfXYWUe2Y3tFylnKk96o17AjWiAEN0XnTtCMnJb/XW6yBpRi5a+bkMH84JF9reEPKlhiAtQp/7S/SAxG7EO/Z8GQfJeIKHXWmzSzUDoZiQgFlxaQ=" # FEC_CF_USERNAME
    - secure: "l6rzmZUWCrbe7QlsmcL/Yqu2aU8OUZgmRXq2/fWzH0OIOZxSTZehl0PuzqnXtijCa4tz+HBYGMWcChUrxr0UlLJ9d0MgYpdbld1D2V64ahXOaR7zAGibvH5raBUtta4YcpztbFQHUiNNbyoouT08Z0LzvvxG9z99Evnm1a5zwwrGlL80lC+t/BlV6eDe1lL7DuJlq74cGpJ9aea3KOctfM0YcnCQtXnc0DHCvTqL1VLJWSuY00mAJ6ZV7wpzpITHvoM4a10QIMPKTUpQ0tRLno3KpbR1TIQOl6IXCgRSJmLbzE+mcwHY882QX3JzzsOCD5ejqXHdUTVdnanl8MHq/acRHoBmsImM85lcHc/BXXv1hYnYLMJGk3wy54IPWaeIzu39MKy3pclBTUMkApiC1NeFGiiIZgeNVW2DlbEVFxwX0cUFscAcb4vKt5m+TaR8iy4R+jUbsN0/jkUiaJXpR0tfYP7jm0zgszCz8iu4BqrRz20P5CYOzr+q9HfPRFtup2KWZcAHtopUje9jyOvr7kRbucMFXe88XAthgwAyhUkvvjFqezVz1jzwMltbx12axGW+/8dXVs4PyszR4pYcsl2v2jvFc65aiNyY6AAKe5b7iAoDyQ+gaePLEjF+ykmLmy8gRBAS+5+r78InAhmYcSlTG0+6w/kaHb/uN0siAYI=" # FEC_CF_PASSWORD
    - secure: "rLuzE+/3WVxra5ssD9MdVqTsuVcRc0PpOrc4FayueQ9y/CcjXuxFtU9NpS88DDwAyGc/7wCPLmRKAzsNTMgDjfHkKXa8VfhI9zZ7HOEI1suVJakkJFXTwajH1X+ACDICoQocrmuOesIMrlAm1qhrSnxHLZuIZ5y3qEGPaSvCMa9JPX9U8huJuhwukxiunpeoApeJclRK7HjLhrAIZVuBNZnyNjiqmNFXPFdGbpcdUGsqNrZQGZa9vlED2dXmqqsIhL7/ghR1sSvIzjVBEi2Ig9wu1QWO5LuAzgO6wIfuOh1gbQ1Z24bYLTeugApwI2eNRe5Rn7F+RXVCYbjetj/0twIXKr6NkSgaLt1c+2b7yIOLRpRl0kpahZc+TsQ3ja03UelpXhH8c0De+6sUvmofs39RgdMSjYBcaY5hDl1b5oZOcZDhQYYAiFUJ3CKIM82WgvTD/phcarf9e0lbrVFIK17P/QixUPAKUS+IfS53r10QO1DTN+0vpLcUh659u8gLxHlbTVkGPfuWRXVhPCmSlHZXqM22gVois5ch97FEm7sgLlJP5hHg1q+utvXV4YDM0m+5SicjGeTyh7ZNszBiMuCu9Na5NaUyhb3XS8niLPwXUzNKcUs0NXckakpqBxstAE4Zyqf3HmmzFQCNvdrFnk6fuRXo1nxtRi1K3N/zf4k=" # DJANGO_SECRET_KEY this is a random key unrelated to prod but needed for django to run build commands with production settings

before_install:
  - travis_retry pip install -U pip setuptools wheel
  - export DATABASE_URL=postgresql://:@/cfdm_cms_unit_test

before_script:
  - psql -c 'create database cfdm_cms_unit_test;' -U postgres
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coverage django_coverage_plugin

  - . $HOME/.nvm/nvm.sh
  - nvm install v5.5.0
  - nvm use v5.5.0

  - travis_retry npm install
  - npm run build

script:
  - (cd fec && coverage run ./manage.py test)
  - npm run test-single

after_success:
  - travis_retry pip install codecov
  # Collect the Python coverage as XML in advance since it needs to run inside
  # the fec dir.
  - (cd fec && coverage xml)
  # Run codecov outside fec dir to include coverage/coverage.json from JS
  # testing, and disable it from running `coverage xml` since that's already
  # done.
  - codecov -X pycov

before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm run build
  - DJANGO_SETTINGS_MODULE='fec.settings.production' python fec/manage.py collectstatic --noinput -v 0
  - DJANGO_SETTINGS_MODULE='fec.settings.production' python fec/manage.py compress -v 0

deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --yes
  on:
    all_branches: true
