language: python

sudo: false

cache: false

python:
  - "3.4"

env:
  global:
    - secure: "yFhH0tX9KqwPKu8qf6CiJvCTO/4uWNanDdbnKlwPR8LWp5TUNRxaF4X9qYVZBKADCR9ScHqUz93Vv8eBa4X3LY6o3JEm4iVjkIZUs0tUrCdANAn3teVepftHjySLskTijXBIMWm/SLMDL7aWfwJqMhXMA1LacacT2kOKTzlP6zVj/aAB2WUletWauL5rD6CXqVxIoobKfR69liEfwHQco7uxQIkTqvTDnhmDHSk/KqUJNwTl6ZypfG3ZedCQleTs1gh2tGqVkMRtKSnpqK5JHCCOgj0VCpJ1IrGERx9CUQbVBifhAA7mywKUMLcuL66Q7aNEJ+MMVonnYlNZI1TX5JblXp+7Ro0QGKiPz9YE7i2gkvVUh8c9tmIQY+WKKTYweQpGvmw7N6QuAzhQkjKKbMFHYJGX+whJ7llpQ/dW4bBpDoHsbYjt4duoptzaxnu/2Vh2ZqrRDvC5lxbul4gUydDpn+jX9ujlS9lb0eduwyTSCnMfcaxO6GwcerbPX5wPSGXOw6dWfnEmMVsXypoG+bj74y8H3rTcQWtwvYM2qpq/oO1jdDYkEcqDP3lkXFSTQ3rPb+rB8AAlLV6D0/eip3LDfXE6kBvkWJysby/coOZ9IUruSK1F1K/cqq9ZHr3tIsrlJddYCYOhicDKUmojIlr5dHOOterUGMZ+D08P1QM=" # FEC_CF_USERNAME
    - secure: "au64J6rsla3I8I+eEmkiZLEVY7hA2qAPDoTvTlNUx2w0lIj0jJnQ+SF/yDTSohpDCTJA/eO4Vaiw4DgyNI4txuSNC7fa4e91I1IHcxGkhQ1+76Z5czM00pTa7MEF6Nz5rimRbhLcKHVcAQ3acbGvUf6xa8XTpoz1gBXTHZOM/MbtDrFwtFIAHX6WJHkTL88sSS+3Zxu3gtkZJj/t07wj+soQDveHhp1IHRKDm3C3mRrMAVT8b8uvYma3sGcMxaCe0aIWD5ijqsBnEMr+GM+vANiv7qzK0nYd2nEraZVCmF4HN7n1PXxUWnHSS5lB1ko9NQpH+Y3A7KVefZaAgPt2SSFjZ4/WMVpKj160Hx33eqECG0fWUA251D9lglF/UO/U9iXb49K4+J9Z+l46ktMfydXQM+OKiR4z/zVldZI/LQrG7taMaFp7TE76e7Ppf9bpd4sH+iOyLC7T3TG2O0LMS78Y3bLNQNH5aqx8qp42la/EkNJUnRwvtxw+m9KPayzlmF5Sac/Fk4vrLXRIkBoul2wLns1EkCIRsUnk3jJGa8dqsaWqzxacYyazPS9e3SWIOfgxH3LyTOysEyZwnj+lR68+o0TtgIAtOD2Ss5AZqTvQEj+jMw6S+oPaiD1GCsSU2ujRZW5RKEWWA4rQjYflFhF/9uiPQslLrygNqWyy+oc=" # FEC_CF_PASSWORD
    - secure: "rLuzE+/3WVxra5ssD9MdVqTsuVcRc0PpOrc4FayueQ9y/CcjXuxFtU9NpS88DDwAyGc/7wCPLmRKAzsNTMgDjfHkKXa8VfhI9zZ7HOEI1suVJakkJFXTwajH1X+ACDICoQocrmuOesIMrlAm1qhrSnxHLZuIZ5y3qEGPaSvCMa9JPX9U8huJuhwukxiunpeoApeJclRK7HjLhrAIZVuBNZnyNjiqmNFXPFdGbpcdUGsqNrZQGZa9vlED2dXmqqsIhL7/ghR1sSvIzjVBEi2Ig9wu1QWO5LuAzgO6wIfuOh1gbQ1Z24bYLTeugApwI2eNRe5Rn7F+RXVCYbjetj/0twIXKr6NkSgaLt1c+2b7yIOLRpRl0kpahZc+TsQ3ja03UelpXhH8c0De+6sUvmofs39RgdMSjYBcaY5hDl1b5oZOcZDhQYYAiFUJ3CKIM82WgvTD/phcarf9e0lbrVFIK17P/QixUPAKUS+IfS53r10QO1DTN+0vpLcUh659u8gLxHlbTVkGPfuWRXVhPCmSlHZXqM22gVois5ch97FEm7sgLlJP5hHg1q+utvXV4YDM0m+5SicjGeTyh7ZNszBiMuCu9Na5NaUyhb3XS8niLPwXUzNKcUs0NXckakpqBxstAE4Zyqf3HmmzFQCNvdrFnk6fuRXo1nxtRi1K3N/zf4k=" # DJANGO_SECRET_KEY this is a random key unrelated to prod but needed for django to run build commands with production settings

before_install:
  - "pip install --upgrade pip setuptools"

before_script:
  - travis_retry pip install -U pip wheel
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coverage django_coverage_plugin

  - . $HOME/.nvm/nvm.sh
  - nvm install v5.5.0
  - nvm use v5.5.0

  - travis_retry npm install
  - npm run build

script:
  - (cd fec && coverage run ./manage.py test)
  - npm run test-single

after_success:
  - travis_retry pip install codecov
  # Collect the Python coverage as XML in advance since it needs to run inside
  # the fec dir.
  - (cd fec && coverage xml)
  # Run codecov outside fec dir to include coverage/coverage.json from JS
  # testing, and disable it from running `coverage xml` since that's already
  # done.
  - codecov -X pycov

before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm run build
  - DJANGO_SETTINGS_MODULE='fec.settings.production' python fec/manage.py collectstatic --noinput
  - DJANGO_SETTINGS_MODULE='fec.settings.production' python fec/manage.py compress

deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --yes
  on:
    all_branches: true
